<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'files' => [
        base_path('app/User.php'),
        base_path('app/ExternalAccount.php'),
        base_path('app/Dictionary.php'),
        base_path('app/File.php'),
        base_path('app/Tag.php'),
        base_path('app/Revision.php'),
        base_path('app/Http/Controllers/Controller.php'),
        base_path('app/Http/Controllers/UsersController.php'),
        base_path('app/Http/Controllers/DictionariesController.php'),
        base_path('app/Http/Controllers/RevisionsController.php'),
        base_path('app/Http/Middleware/HTTPStatus.php'),
        base_path('app/Http/Middleware/Polyfill.php'),
        base_path('app/Providers/AppServiceProvider.php'),
        base_path('app/Providers/HtmlServiceProvider.php'),
        base_path('app/Providers/MacroServiceProvider.php'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'providers' => [
        //
    ],

];
